import React, { useEffect, useState } from 'react';
import { Bell, Bookmark, Building2, CheckCircle2, FileText, GraduationCap, LayoutDashboard, LogOut, Search, User, Users } from 'lucide-react';
const API = process.env.REACT_APP_API_URL || 'http://localhost:5000';
async function api(path, options = {}) { const response = await fetch(`${API}${path}`, { credentials: 'include', headers: { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...options.headers }, ...options }); const body = await response.json().catch(() => ({})); if (!response.ok || body.success === false) throw new Error(body.message || 'The request could not be completed.'); return body.data; }
const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value || 0));
const Status = ({ children }) => <span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700">{String(children || '').replaceAll('_',' ')}</span>;

export default function App() { const [user,setUser]=useState(null),[page,setPage]=useState('dashboard'),[error,setError]=useState(''),[toast,setToast]=useState('');
  useEffect(()=>{api('/api/auth/me').then(setUser).catch(()=>setUser(null));},[]);
  const done = message => { setToast(message); setTimeout(()=>setToast(''),3500); };
  if (!user) return <Auth onLogin={u=>{setUser(u);setPage('dashboard');}} />;
  const student = user.role==='STUDENT', institution=user.role==='INSTITUTION';
  const nav = student ? [['dashboard',LayoutDashboard,'Dashboard'],['profile',User,'Profile'],['scholarships',GraduationCap,'Scholarships'],['recommendations',CheckCircle2,'Recommendations'],['eligibility',CheckCircle2,'Eligibility checker'],['applications',FileText,'My applications'],['saved',Bookmark,'Saved scholarships'],['notifications',Bell,'Notifications']] : institution ? [['dashboard',LayoutDashboard,'Dashboard'],['institution',Building2,'Verification queue'],['notifications',Bell,'Notifications']] : [['dashboard',LayoutDashboard,'Admin dashboard'],['adminUsers',Users,'User management'],['adminScholarships',GraduationCap,'Scholarship management'],['notifications',Bell,'Notifications']];
  return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-4 py-3 lg:px-8"><button onClick={()=>setPage('dashboard')} className="flex items-center gap-3 text-left"><span className="rounded-xl bg-indigo-700 p-2 text-white"><GraduationCap /></span><span><b className="block">ScholarPath</b><small className="text-slate-500">Scholarship management portal</small></span></button><div className="flex items-center gap-3"><button onClick={()=>setPage('notifications')} aria-label="Notifications" className="rounded-lg p-2 hover:bg-slate-100"><Bell size={19}/></button><button onClick={()=>setPage('profile')} aria-label="Profile" className="rounded-full bg-indigo-100 p-2 text-indigo-700"><User size={18}/></button><button onClick={async()=>{await api('/api/auth/logout',{method:'POST'});setUser(null);}} className="flex items-center gap-1 text-sm font-medium text-slate-600"><LogOut size={17}/> <span className="hidden sm:inline">Logout</span></button></div></header><div className="mx-auto flex max-w-7xl"><aside className="hidden w-60 shrink-0 border-r bg-white p-4 md:block"><p className="mb-5 px-3 text-xs font-semibold uppercase tracking-wider text-slate-400">{user.role.toLowerCase()} portal</p>{nav.map(([key,Icon,label])=><button key={key} onClick={()=>setPage(key)} className={`mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm ${page===key?'bg-indigo-50 font-semibold text-indigo-700':'text-slate-600 hover:bg-slate-50'}`}><Icon size={18}/>{label}</button>)}</aside><main className="min-w-0 flex-1 p-4 md:p-8">{error&&<Alert message={error} onClose={()=>setError('')}/>} {toast&&<div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{toast}</div>} {page==='dashboard'&&<Dashboard user={user} onPage={setPage}/>} {page==='profile'&&student&&<Profile done={done} fail={setError}/>} {page==='scholarships'&&student&&<Scholarships done={done} fail={setError}/>} {page==='recommendations'&&student&&<Recommendations fail={setError}/>} {page==='eligibility'&&student&&<Eligibility fail={setError}/>} {page==='applications'&&student&&<Applications done={done} fail={setError}/>} {page==='saved'&&student&&<Saved fail={setError}/>} {page==='notifications'&&<Notifications fail={setError}/>} {page==='institution'&&institution&&<Institution done={done} fail={setError}/>} {page==='adminUsers'&&!student&&!institution&&<AdminUsers fail={setError}/>} {page==='adminScholarships'&&!student&&!institution&&<AdminScholarships done={done} fail={setError}/>}</main></div></div>;
}
function Auth({onLogin}) { const [mode,setMode]=useState('login'),[form,setForm]=useState({fullName:'',email:'',password:'',role:'STUDENT',institutionName:'',institutionCode:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false); const change=e=>setForm({...form,[e.target.name]:e.target.value}); const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{if(mode==='register')await api('/api/auth/register',{method:'POST',body:JSON.stringify(form)});const user=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:form.email,password:form.password})});onLogin(user);}catch(e){setError(e.message);}finally{setBusy(false);}}; return <div className="grid min-h-screen place-items-center bg-gradient-to-br from-indigo-950 to-indigo-700 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-7 shadow-xl"><div className="mb-6 flex items-center gap-3"><span className="rounded-xl bg-indigo-700 p-2 text-white"><GraduationCap/></span><div><h1 className="text-xl font-bold">ScholarPath</h1><p className="text-sm text-slate-500">{mode==='login'?'Welcome back':'Create your portal account'}</p></div></div>{error&&<Alert message={error}/>} {mode==='register'&&<><Field label="Full name" name="fullName" value={form.fullName} onChange={change}/><label className="mb-4 block text-sm font-medium">Account type<select name="role" value={form.role} onChange={change} className="mt-1 w-full rounded-lg border p-2.5"><option value="STUDENT">Student</option><option value="INSTITUTION">Institution</option></select></label>{form.role==='INSTITUTION'&&<><Field label="Institution name" name="institutionName" value={form.institutionName} onChange={change}/><Field label="Institution code" name="institutionCode" value={form.institutionCode} onChange={change}/></>}</>}<Field label="Email" type="email" name="email" value={form.email} onChange={change}/><Field label="Password" type="password" name="password" value={form.password} onChange={change} hint={mode==='register'?'At least 10 characters, with letters and numbers':''}/><button disabled={busy} className="w-full rounded-lg bg-indigo-700 py-2.5 font-semibold text-white disabled:opacity-60">{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button><button type="button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('');}} className="mt-4 w-full text-sm text-indigo-700">{mode==='login'?'New here? Create an account':'Already registered? Sign in'}</button></form></div>; }
function Field({label,hint,...props}) { return <label className="mb-4 block text-sm font-medium">{label}<input required className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 outline-indigo-600" {...props}/>{hint&&<small className="mt-1 block font-normal text-slate-500">{hint}</small>}</label>; }
function Alert({message,onClose}) { return <div className="mb-4 flex justify-between rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><span>{message}</span>{onClose&&<button onClick={onClose}>×</button>}</div>; }
function Card({children}) { return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">{children}</section>; }
function Dashboard({user,onPage}) { const [data,setData]=useState(null),[error,setError]=useState(''); useEffect(()=>{ const path=user.role==='ADMIN'?'/api/admin/analytics':user.role==='INSTITUTION'?'/api/institution/applications':'/api/applications'; api(path).then(setData).catch(e=>setError(e.message));},[user.role]); if(error)return <Alert message={error}/>; if(!data)return <Loading/>; if(user.role==='ADMIN'){const s=data.stats;return <><Title title="Administration overview" text="Live metrics from your portal database."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(s).map(([k,v])=><Metric key={k} label={k} value={v}/>)}</div><Card><h2 className="mb-3 font-bold">Applications by scholarship</h2>{data.byScholarship.map(x=><p className="flex justify-between border-t py-2 text-sm" key={x.name}><span>{x.name}</span><b>{x.applications}</b></p>)}</Card></>;} if(user.role==='INSTITUTION'){
  const pendingVerification = data.filter(
    x => x.status === 'INSTITUTION_VERIFICATION'
  ).length;

  return (
    <>
      <Title
        title={`Welcome, ${user.fullName}`}
        text="Review only applications assigned to your institution."
      />

      <Metric
        label="Pending verification"
        value={pendingVerification}
      />

      <button
        onClick={() => onPage('institution')}
        className="mt-4 rounded-lg bg-indigo-700 px-4 py-2 text-white"
      >
        Open verification queue
      </button>
    </>
  );
} return <><Title title={`Welcome, ${user.fullName}`} text="Keep your profile current and apply before scholarship deadlines."/><div className="grid gap-4 sm:grid-cols-3"><Metric label="My applications" value={data.length}/><Metric label="Active applications" value={data.filter(x=>!['APPROVED','REJECTED'].includes(x.status)).length}/><Metric label="Next step" value="Profile"/></div><Card><h2 className="font-bold">Get started</h2><p className="mt-1 text-sm text-slate-600">A complete profile and documents are required before submitting an application.</p><div className="mt-4 flex gap-3"><button onClick={()=>onPage('profile')} className="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold text-white">Complete profile</button><button onClick={()=>onPage('scholarships')} className="rounded-lg border px-4 py-2 text-sm font-semibold">Browse scholarships</button></div></Card></>; }
const Metric=({label,value})=><Card><p className="text-sm capitalize text-slate-500">{label.replaceAll('_',' ')}</p><p className="mt-2 text-3xl font-bold">{value}</p></Card>;
const Title=({title,text})=><div className="mb-6"><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-slate-600">{text}</p></div>;
const Loading=()=> <p className="p-8 text-center text-slate-500">Loading…</p>;
function Profile({done,fail}) { const [form,setForm]=useState(null);useEffect(()=>{api('/api/profile').then(setForm).catch(e=>fail(e.message));},[fail]);if(!form)return <Loading/>;const change=e=>setForm({...form,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value});return <><Title title="My profile" text="Only information needed for eligibility and applications is collected."/><form onSubmit={async e=>{e.preventDefault();try{await api('/api/profile',{method:'PUT',body:JSON.stringify(form)});done('Profile saved.');}catch(e){fail(e.message);}}} className="grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-2">{[['Full name','fullName'],['Phone','phone'],['Date of birth','dateOfBirth','date'],['Gender','gender'],['Community/category','community'],['Religion','religion'],['Annual income','annualIncome','number'],['Citizenship','citizenship'],['State','state'],['Qualification','qualification'],['Institution name','institutionName'],['Course','course'],['Percentage','percentage','number'],['Graduation year','graduationYear','number']].map(([label,name,type])=><Field key={name} label={label} name={name} type={type||'text'} value={form[name]||''} onChange={change}/>)}<div className="flex gap-5 md:col-span-2">{[['disability','Disability'],['sports','Sports participation'],['exServicemen','Ex-servicemen dependent']].map(([name,label])=><label key={name} className="flex items-center gap-2 text-sm"><input name={name} type="checkbox" checked={Boolean(form[name])} onChange={change}/>{label}</label>)}</div><button className="rounded-lg bg-indigo-700 px-4 py-2 font-semibold text-white md:col-span-2">Save profile</button></form></>; }
function Scholarships({done,fail}) { const [result,setResult]=useState(null),[q,setQ]=useState('');const load=()=>api(`/api/scholarships?q=${encodeURIComponent(q)}`).then(setResult).catch(e=>fail(e.message));useEffect(()=>{load();},[]);if(!result)return <Loading/>;return <><Title title="Discover scholarships" text="Search the live scholarship catalog and save opportunities."/><div className="mb-5 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search provider, name, or keyword" className="flex-1 rounded-lg border p-2.5"/><button onClick={load} className="rounded-lg bg-indigo-700 px-4 text-white"><Search size={18}/></button></div><div className="grid gap-4 lg:grid-cols-2">{result.items.map(s=><ScholarshipCard key={s.id} s={s} done={done} fail={fail}/>)}</div>{!result.items.length&&<Card>No open scholarships match your search.</Card>}</>; }
function ScholarshipCard({s,done,fail}) { const [detail,setDetail]=useState(false);return <Card><div className="flex justify-between gap-3"><div><h2 className="font-bold">{s.name}</h2><p className="mt-1 text-sm text-slate-500">{s.provider}</p></div><Status>{s.status}</Status></div><p className="mt-3 line-clamp-2 text-sm text-slate-600">{s.description}</p><div className="mt-4 flex flex-wrap gap-3 text-sm"><b>{money(s.amount)}</b><span>Deadline: {String(s.end_date).slice(0,10)}</span></div><div className="mt-4 flex gap-2"><button onClick={()=>setDetail(!detail)} className="rounded-lg border px-3 py-2 text-sm">{detail?'Hide details':'Details'}</button><button onClick={async()=>{try{await api(`/api/scholarships/${s.id}/save`,{method:'POST'});done('Saved to your list.');}catch(e){fail(e.message);}}} className="rounded-lg border px-3 py-2 text-sm"><Bookmark size={15}/></button><Apply id={s.id} done={done} fail={fail}/></div>{detail&&<ScholarshipDetail id={s.id} fail={fail}/>}</Card>; }
function ScholarshipDetail({id,fail}) { const [data,setData]=useState(null);useEffect(()=>{api(`/api/scholarships/${id}`).then(setData).catch(e=>fail(e.message));},[id,fail]);if(!data)return <Loading/>;return <div className="mt-4 border-t pt-4 text-sm"><p className="whitespace-pre-line">{data.description}</p><h3 className="mt-3 font-semibold">Required documents</h3><p>{data.requiredDocuments.map(x=>x.document_name).join(', ')||'Refer to provider instructions.'}</p></div>; }
function Apply({id,done,fail}) { const [application,setApplication]=useState(null),[files,setFiles]=useState([]),[type,setType]=useState('Government ID');const create=async()=>{try{setApplication(await api('/api/applications',{method:'POST',body:JSON.stringify({scholarshipId:id})}));done('Draft application created. Upload a document, then submit.');}catch(e){fail(e.message);}}; if(!application)return <button onClick={create} className="rounded-lg bg-indigo-700 px-3 py-2 text-sm font-semibold text-white">Apply</button>; return <div className="mt-3 w-full rounded-lg bg-slate-50 p-3"><p className="text-sm font-medium">Draft {application.publicId}</p><select value={type} onChange={e=>setType(e.target.value)} className="mt-2 rounded border p-1 text-sm"><option>Government ID</option><option>Marksheet</option><option>Income certificate</option><option>Community certificate</option></select><input className="mt-2 block text-sm" type="file" multiple accept="application/pdf,image/jpeg,image/png" onChange={e=>setFiles([...e.target.files])}/><div className="mt-2 flex gap-2"><button onClick={async()=>{const form=new FormData();form.append('documentType',type);files.forEach(f=>form.append('files',f));try{await api(`/api/applications/${application.id}/documents`,{method:'POST',body:form});done('Document uploaded.');}catch(e){fail(e.message);}}} className="rounded bg-white px-2 py-1 text-sm">Upload</button><button onClick={async()=>{try{await api(`/api/applications/${application.id}/submit`,{method:'POST'});done('Application submitted.');}catch(e){fail(e.message);}}} className="rounded bg-indigo-700 px-2 py-1 text-sm text-white">Submit</button></div></div>; }
function Recommendations({fail}) { const [items,setItems]=useState(null);useEffect(()=>{api('/api/recommendations').then(setItems).catch(e=>fail(e.message));},[fail]);if(!items)return <Loading/>;return <><Title title="Recommended for you" text="These are rule-based matches; official criteria remain decisive."/><div className="grid gap-4 lg:grid-cols-2">{items.map(x=><Card key={x.scholarship.id}><h2 className="font-bold">{x.scholarship.name}</h2><p className="mt-1 text-sm text-slate-500">{x.scholarship.provider}</p><ul className="mt-3 list-inside list-disc text-sm text-emerald-700">{x.reasons.map(r=><li key={r}>{r}</li>)}</ul></Card>)}</div>{!items.length&&<Card>Complete more of your profile to get recommendations.</Card>}</>; }
function Eligibility({ fail }) {
  const [result, setResult] = useState(null);
  const [checking, setChecking] = useState(false);

  return (
    <>
      <Title
        title="AI eligibility checker"
        text="An advisory prediction based on your profile—not an official decision."
      />

      <Card>
        <p className="text-sm text-slate-600">
          Your saved profile is sent to the trained model without your name.
          Complete the profile first, then run the check.
        </p>

        <button
          disabled={checking}
          onClick={async () => {
            setChecking(true);

            try {
              setResult(
                await api('/api/eligibility', {
                  method: 'POST'
                })
              );
            } catch (e) {
              fail(e.message);
            } finally {
              setChecking(false);
            }
          }}
          className="mt-4 rounded-lg bg-indigo-700 px-4 py-2 font-semibold text-white disabled:opacity-50"
        >
          {checking ? 'Checking…' : 'Check eligibility'}
        </button>

        {result && (
          <div
            className={`mt-4 rounded-lg p-4 ${
              result.eligible_prediction
                ? 'bg-emerald-50 text-emerald-800'
                : 'bg-amber-50 text-amber-800'
            }`}
          >
            <b>
              {result.eligible_prediction
                ? 'Potentially eligible'
                : 'Not eligible according to the AI prediction'}
            </b>

            <p className="mt-1 text-sm">
              AI probability:{' '}
              {(result.eligible_probability * 100).toFixed(2)}%
            </p>

            <p className="mt-1 text-sm">
              {result.notice}
            </p>
          </div>
        )}
      </Card>
    </>
  );
}


function Applications({done,fail}) { const [items,setItems]=useState(null),[selected,setSelected]=useState(null);const load=()=>api('/api/applications').then(setItems).catch(e=>fail(e.message));useEffect(()=>{load();},[]);if(!items)return <Loading/>;return <><Title title="My applications" text="Track every stage and any verification remarks."/><div className="space-y-3">{items.map(a=><Card key={a.id}><button className="flex w-full justify-between text-left" onClick={()=>api(`/api/applications/${a.id}`).then(setSelected).catch(e=>fail(e.message))}><span><b className="block">{a.scholarship_name}</b><small>{a.public_id}</small></span><Status>{a.status}</Status></button></Card>)}</div>{selected&&<Card><h2 className="font-bold">Application timeline</h2><div className="mt-3 space-y-3 border-l-2 border-indigo-200 pl-4">{selected.history.map(h=><div key={h.id}><b className="text-sm"><Status>{h.status}</Status></b><p className="mt-1 text-sm">{h.remarks}</p><small className="text-slate-500">{String(h.created_at).replace('T',' ').slice(0,16)}</small></div>)}</div><h3 className="mt-4 font-semibold">Documents</h3>{selected.documents.map(d=><p key={d.id} className="mt-2 text-sm"><Status>{d.status}</Status> {d.original_name}</p>)}</Card>}{!items.length&&<Card>No applications yet.</Card>}</>; }
function Saved({fail}) { const [items,setItems]=useState(null);useEffect(()=>{api('/api/saved-scholarships').then(setItems).catch(e=>fail(e.message));},[fail]);if(!items)return <Loading/>;return <><Title title="Saved scholarships" text="Opportunities you bookmarked for later."/><div className="grid gap-4 lg:grid-cols-2">{items.map(s=><Card key={s.id}><h2 className="font-bold">{s.name}</h2><p className="text-sm text-slate-500">{s.provider}</p><p className="mt-2 text-sm">Deadline: {String(s.end_date).slice(0,10)}</p></Card>)}</div>{!items.length&&<Card>You have not saved any scholarships yet.</Card>}</>; }
function Notifications({fail}) { const [items,setItems]=useState(null);useEffect(()=>{api('/api/notifications').then(setItems).catch(e=>fail(e.message));},[fail]);if(!items)return <Loading/>;return <><Title title="Notifications" text="Updates about your account and applications."/><div className="space-y-3">{items.map(x=><Card key={x.id}><div className="flex justify-between gap-4"><div><h2 className="font-semibold">{x.title}</h2><p className="mt-1 text-sm text-slate-600">{x.message}</p>{x.scholarship_name&&x.application_public_id&&<p className="mt-1 text-xs text-slate-500">{x.scholarship_name} · {x.application_public_id}</p>}<small className="text-slate-400">{String(x.created_at).replace('T',' ').slice(0,16)}</small></div>{!x.is_read&&<button onClick={async()=>{try{await api(`/api/notifications/${x.id}/read`,{method:'PATCH'});setItems(items.map(i=>i.id===x.id?{...i,is_read:true}:i));}catch(e){fail(e.message);}}} className="h-fit text-xs text-indigo-700">Mark read</button>}</div></Card>)}</div>{!items.length&&<Card>No notifications yet.</Card>}</>; }
function Institution({done,fail}) { const [items,setItems]=useState(null);const load=()=>api('/api/institution/applications').then(setItems).catch(e=>fail(e.message));useEffect(()=>{load();},[]);if(!items)return <Loading/>;return <><Title title="Verification queue" text="Only applications linked to your institution are shown."/><div className="space-y-3">{items.map(x=><Card key={x.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{x.student_name}</h2><p className="text-sm text-slate-600">{x.scholarship_name}</p><small>{x.public_id}</small></div><Status>{x.status}</Status></div><textarea id={`remark-${x.id}`} placeholder="Verification remarks" className="mt-3 w-full rounded border p-2 text-sm"/><div className="mt-2 flex gap-2">{[['VERIFIED','Verify'],['CORRECTION_REQUIRED','Request correction'],['REJECTED','Reject']].map(([decision,label])=><button key={decision} onClick={async()=>{try{await api(`/api/institution/applications/${x.id}/verify`,{method:'POST',body:JSON.stringify({decision,remarks:document.getElementById(`remark-${x.id}`).value})});done(`Application ${decision.toLowerCase().replaceAll('_',' ')}.`);load();}catch(e){fail(e.message);}}} className={`rounded px-3 py-2 text-sm ${decision==='VERIFIED'?'bg-emerald-600 text-white':'border'}`}>{label}</button>)}</div></Card>)}</div>{!items.length&&<Card>Your verification queue is clear.</Card>}</>; }
function AdminUsers({fail}) { const [items,setItems]=useState(null),[filter,setFilter]=useState('');const load=()=>api(`/api/admin/users${filter?`?role=${filter}`:''}`).then(setItems).catch(e=>fail(e.message));useEffect(()=>{load();},[filter]);if(!items)return <Loading/>;return <><Title title="User management" text="Activate or deactivate accounts with appropriate administrative authority."/><select value={filter} onChange={e=>setFilter(e.target.value)} className="mb-4 rounded border p-2 text-sm"><option value="">All roles</option><option>STUDENT</option><option>INSTITUTION</option><option>ADMIN</option></select><Card><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-2">Name</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-b"><td className="p-2">{x.full_name}</td><td>{x.email}</td><td><Status>{x.role}</Status></td><td>{x.is_active?'Active':'Inactive'}</td><td><button onClick={async()=>{try{await api(`/api/admin/users/${x.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:!x.is_active})});load();}catch(e){fail(e.message);}}} className="text-indigo-700">{x.is_active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></Card></>; }
function AdminScholarships({done,fail}) { const [form,setForm]=useState({name:'',provider:'',description:'',type:'Merit',amount:'',category:'',course:'',state:'',startDate:'',endDate:'',status:'active'});const c=e=>setForm({...form,[e.target.name]:e.target.value});return <><Title title="Scholarship management" text="Create real catalog entries. Configure detailed criteria and documents in the database."/><form onSubmit={async e=>{e.preventDefault();try{await api('/api/admin/scholarships',{method:'POST',body:JSON.stringify(form)});done('Scholarship created.');setForm({...form,name:'',description:''});}catch(e){fail(e.message);}}} className="grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-2">{[['Name','name'],['Provider','provider'],['Type','type'],['Amount','amount','number'],['Category','category'],['Eligible course','course'],['State/location','state'],['Start date','startDate','date'],['Deadline','endDate','date']].map(([label,name,type])=><Field key={name} label={label} name={name} type={type||'text'} value={form[name]} onChange={c}/>)}<label className="md:col-span-2 text-sm font-medium">Description<textarea required name="description" value={form.description} onChange={c} className="mt-1 min-h-28 w-full rounded-lg border p-2.5"/></label><button className="rounded-lg bg-indigo-700 px-4 py-2 font-semibold text-white md:col-span-2">Create scholarship</button></form></>; }
